language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy-5.4.1"

sudo: false
env:
  - CASS_DRIVER_NO_CYTHON=1

addons:
  apt:
    packages:
    - build-essential
    - python-dev
    - pypy-dev
    - libc-ares-dev
    - libev4
    - libev-dev

install:
  - pip install tox-travis lz4

script:
  - tox
  - tox -e gevent_loop
  - tox -e eventlet_loop
